"""Initial migration for server2

Revision ID: 047a4435bd80
Revises: 
Create Date: 2025-11-13 23:36:17.935441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '047a4435bd80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_name', sa.String(length=255), nullable=False),
    sa.Column('certificate_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificates_certificate_name'), 'certificates', ['certificate_name'], unique=True)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_table('internal_asset_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.Enum('HARDWARE_COMPONENT', 'PERISHABLE_GOOD', name='asset_class'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('pin_connection_type', sa.Enum('GPIO', 'I2C', 'SPI', 'UART', 'ANALOG', name='pin_connection_type'), nullable=True),
    sa.Column('default_pin_count', sa.Integer(), nullable=True),
    sa.Column('estimated_lifespan_days', sa.Integer(), nullable=True),
    sa.Column('typical_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_number')
    )
    op.create_index(op.f('ix_internal_asset_definitions_id'), 'internal_asset_definitions', ['id'], unique=False)
    op.create_table('organization_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_index(op.f('ix_organization_types_id'), 'organization_types', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('product_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enforce_device_limit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_product_lines_id'), 'product_lines', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_yearly', sa.Float(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_table('supported_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('telemetry_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supported_components_component_type'), 'supported_components', ['component_type'], unique=True)
    op.create_index(op.f('ix_supported_components_id'), 'supported_components', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('shared_secret', sa.String(length=255), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', name='log_event_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('log_level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'), nullable=True, comment='로그 심각도 (선택적)'),
    sa.Column('description', sa.Text(), nullable=True, comment='로그 설명/메시지'),
    sa.Column('user_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('hardware_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_version', sa.String(length=50), nullable=False),
    sa.Column('blueprint_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_line_id'], ['product_lines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_version', 'blueprint_name', name='_blueprint_version_name_uc')
    )
    op.create_index(op.f('ix_hardware_blueprints_id'), 'hardware_blueprints', ['id'], unique=False)
    op.create_table('internal_asset_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('last_updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('asset_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['internal_asset_definitions.id'], ),
    sa.ForeignKeyConstraint(['last_updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_definition_id', 'location', name='_asset_location_uc')
    )
    op.create_index(op.f('ix_internal_asset_inventory_id'), 'internal_asset_inventory', ['id'], unique=False)
    op.create_table('internal_asset_purchase_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price_per_unit', sa.Float(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invoice_number', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('asset_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['internal_asset_definitions.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_asset_purchase_records_id'), 'internal_asset_purchase_records', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('business_registration_number', sa.String(length=50), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('main_contact_person', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.Enum('KRW', 'USD', name='currency_type'), nullable=True),
    sa.Column('pg_customer_id', sa.String(length=255), nullable=True),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('representative_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('billing_address', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_type_id'], ['organization_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_registration_number')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('subscription_plan_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False),
    sa.Column('feature_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'feature_key', name='_plan_feature_uc')
    )
    op.create_index(op.f('ix_subscription_plan_features_id'), 'subscription_plan_features', ['id'], unique=False)
    op.create_table('supported_component_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=100), nullable=False),
    sa.Column('meta_value', sa.Text(), nullable=False),
    sa.Column('meta_value_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'ENUM', 'JSON', name='meta_value_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('supported_component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supported_component_id'], ['supported_components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supported_component_id', 'meta_key', name='_component_meta_uc')
    )
    op.create_index(op.f('ix_supported_component_metadata_id'), 'supported_component_metadata', ['id'], unique=False)
    op.create_table('user_consumables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('asset_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['internal_asset_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consumables_id'), 'user_consumables', ['id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'plan_id', name='_user_plan_uc')
    )
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_table('audit_log_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_log_id', sa.Integer(), nullable=False),
    sa.Column('detail_key', sa.String(length=100), nullable=False),
    sa.Column('detail_value', sa.Text(), nullable=False),
    sa.Column('detail_value_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'ENUM', 'JSON', name='detail_value_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_log_id', 'detail_key', name='_audit_detail_uc')
    )
    op.create_index(op.f('ix_audit_log_details_id'), 'audit_log_details', ['id'], unique=False)
    op.create_table('blueprint_pin_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_name', sa.String(length=50), nullable=False),
    sa.Column('pin_number', sa.Integer(), nullable=True),
    sa.Column('pin_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hardware_blueprint_id', sa.Integer(), nullable=False),
    sa.Column('supported_component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], ),
    sa.ForeignKeyConstraint(['supported_component_id'], ['supported_components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hardware_blueprint_id', 'supported_component_id', 'pin_name', name='_blueprint_component_pin_uc')
    )
    op.create_index(op.f('ix_blueprint_pin_mappings_id'), 'blueprint_pin_mappings', ['id'], unique=False)
    op.create_table('blueprint_valid_pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_number', sa.Integer(), nullable=False),
    sa.Column('pin_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hardware_blueprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hardware_blueprint_id', 'pin_number', name='_blueprint_valid_pin_uc')
    )
    op.create_index(op.f('ix_blueprint_valid_pins_id'), 'blueprint_valid_pins', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_serial', sa.String(length=255), nullable=False),
    sa.Column('current_uuid', sa.UUID(), nullable=False),
    sa.Column('device_certificate_id', sa.Integer(), nullable=True),
    sa.Column('ca_certificate_id', sa.Integer(), nullable=True),
    sa.Column('visibility_status', sa.Enum('PRIVATE', 'ORGANIZATION', 'PUBLIC', name='device_visibility'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('hardware_blueprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ca_certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['device_certificate_id'], ['certificates.id'], ),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_certificate_id')
    )
    op.create_index('idx_device_org_blueprint', 'devices', ['organization_id', 'hardware_blueprint_id'], unique=False)
    op.create_index(op.f('ix_devices_cpu_serial'), 'devices', ['cpu_serial'], unique=True)
    op.create_index(op.f('ix_devices_current_uuid'), 'devices', ['current_uuid'], unique=True)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('internal_blueprint_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('hardware_blueprint_id', sa.Integer(), nullable=False),
    sa.Column('asset_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['internal_asset_definitions.id'], ),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hardware_blueprint_id', 'asset_definition_id', name='_blueprint_asset_uc')
    )
    op.create_index(op.f('ix_internal_blueprint_components_id'), 'internal_blueprint_components', ['id'], unique=False)
    op.create_table('organization_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_devices', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plan_id', name='_org_plan_uc')
    )
    op.create_index(op.f('ix_organization_subscriptions_id'), 'organization_subscriptions', ['id'], unique=False)
    op.create_table('plan_applicable_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('hardware_blueprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'hardware_blueprint_id', name='_plan_blueprint_uc')
    )
    op.create_index(op.f('ix_plan_applicable_blueprints_id'), 'plan_applicable_blueprints', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Enum('SYSTEM', 'ORGANIZATION', name='role_scope'), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('lineage', sa.String(length=20), nullable=True),
    sa.Column('numbering', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='_organization_role_name_uc')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_tier'), 'roles', ['tier'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('notification_channels', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_table('blueprint_pin_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail_key', sa.String(length=100), nullable=False),
    sa.Column('detail_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blueprint_pin_mapping_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_pin_mapping_id'], ['blueprint_pin_mappings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_pin_mapping_id', 'detail_key', name='_pin_detail_uc')
    )
    op.create_index(op.f('ix_blueprint_pin_details_id'), 'blueprint_pin_details', ['id'], unique=False)
    op.create_table('consumable_replacement_events',
    sa.Column('id', sa.Integer(), nullable=False, comment='소모품 교체 이벤트의 고유 ID'),
    sa.Column('replacement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_consumable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_consumable_id'], ['user_consumables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_replacement_events_id'), 'consumable_replacement_events', ['id'], unique=False)
    op.create_table('consumable_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_used', sa.Float(), nullable=False),
    sa.Column('event_type', sa.Enum('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', name='log_event_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('log_level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'), nullable=True, comment='로그 심각도 (선택적)'),
    sa.Column('description', sa.Text(), nullable=True, comment='로그 설명/메시지'),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_consumable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_consumable_id'], ['user_consumables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_usage_logs_id'), 'consumable_usage_logs', ['id'], unique=False)
    op.create_table('device_component_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('supported_component_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['supported_component_id'], ['supported_components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'supported_component_id', 'instance_name', name='_device_component_instance_uc')
    )
    op.create_index(op.f('ix_device_component_instances_id'), 'device_component_instances', ['id'], unique=False)
    op.create_table('device_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('event_type', sa.Enum('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', name='log_event_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('log_level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'), nullable=True, comment='로그 심각도 (선택적)'),
    sa.Column('description', sa.Text(), nullable=True, comment='로그 설명/메시지'),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_logs_id'), 'device_logs', ['id'], unique=False)
    op.create_table('firmware_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('update_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'ROLLBACK', name='update_status'), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('initiated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hardware_blueprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], ),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firmware_updates_id'), 'firmware_updates', ['id'], unique=False)
    op.create_table('internal_component_replacement_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('replacement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('asset_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['internal_asset_definitions.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_component_replacement_events_id'), 'internal_component_replacement_events', ['id'], unique=False)
    op.create_table('production_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('HARVEST', 'GROWTH_UPDATE', 'MAINTENANCE', name='production_event_type'), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yield_amount', sa.Float(), nullable=True),
    sa.Column('crop_type', sa.String(length=50), nullable=True),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('hardware_blueprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_events_id'), 'production_events', ['id'], unique=False)
    op.create_table('registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('requested_role_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_registration_requests_id'), 'registration_requests', ['id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allowed_columns', sa.JSON(), nullable=True),
    sa.Column('filter_condition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='_role_permission_uc')
    )
    op.create_index(op.f('ix_role_permissions_id'), 'role_permissions', ['id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_pattern', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_table('telemetry_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_telemetry_device_time', 'telemetry_data', ['device_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_data_id'), 'telemetry_data', ['id'], unique=False)
    op.create_table('trigger_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_rules_id'), 'trigger_rules', ['id'], unique=False)
    op.create_table('upgrade_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('requested_role_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upgrade_requests_id'), 'upgrade_requests', ['id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='_user_device_uc')
    )
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_table('user_organization_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', 'role_id', name='_user_org_role_uc')
    )
    op.create_index(op.f('ix_user_organization_roles_id'), 'user_organization_roles', ['id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('alert_rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_id'), 'alert_events', ['id'], unique=False)
    op.create_table('device_component_pin_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_name', sa.String(length=50), nullable=False),
    sa.Column('pin_number', sa.Integer(), nullable=False),
    sa.Column('pin_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_component_instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_component_instance_id'], ['device_component_instances.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_component_instance_id', 'pin_name', name='_device_component_pin_uc')
    )
    op.create_index(op.f('ix_device_component_pin_mappings_id'), 'device_component_pin_mappings', ['id'], unique=False)
    op.create_table('image_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('detected_disease', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('analysis_type', sa.Enum('YOLO', 'CLASSIFICATION', 'OTHER', name='analysis_type'), nullable=False),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('production_event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['production_event_id'], ['production_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_analyses_id'), 'image_analyses', ['id'], unique=False)
    op.create_table('telemetry_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telemetry_data_id', sa.Integer(), nullable=False),
    sa.Column('meta_key', sa.String(length=100), nullable=False),
    sa.Column('meta_value', sa.Text(), nullable=False),
    sa.Column('meta_value_type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'ENUM', 'JSON', name='metadata_value_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telemetry_data_id'], ['telemetry_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telemetry_data_id', 'meta_key', name='_telemetry_meta_uc')
    )
    op.create_index(op.f('ix_telemetry_metadata_id'), 'telemetry_metadata', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_metadata_id'), table_name='telemetry_metadata')
    op.drop_table('telemetry_metadata')
    op.drop_index(op.f('ix_image_analyses_id'), table_name='image_analyses')
    op.drop_table('image_analyses')
    op.drop_index(op.f('ix_device_component_pin_mappings_id'), table_name='device_component_pin_mappings')
    op.drop_table('device_component_pin_mappings')
    op.drop_index(op.f('ix_alert_events_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_user_organization_roles_id'), table_name='user_organization_roles')
    op.drop_table('user_organization_roles')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_upgrade_requests_id'), table_name='upgrade_requests')
    op.drop_table('upgrade_requests')
    op.drop_index(op.f('ix_trigger_rules_id'), table_name='trigger_rules')
    op.drop_table('trigger_rules')
    op.drop_index(op.f('ix_telemetry_data_id'), table_name='telemetry_data')
    op.drop_index('idx_telemetry_device_time', table_name='telemetry_data')
    op.drop_table('telemetry_data')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_role_permissions_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_registration_requests_id'), table_name='registration_requests')
    op.drop_table('registration_requests')
    op.drop_index(op.f('ix_production_events_id'), table_name='production_events')
    op.drop_table('production_events')
    op.drop_index(op.f('ix_internal_component_replacement_events_id'), table_name='internal_component_replacement_events')
    op.drop_table('internal_component_replacement_events')
    op.drop_index(op.f('ix_firmware_updates_id'), table_name='firmware_updates')
    op.drop_table('firmware_updates')
    op.drop_index(op.f('ix_device_logs_id'), table_name='device_logs')
    op.drop_table('device_logs')
    op.drop_index(op.f('ix_device_component_instances_id'), table_name='device_component_instances')
    op.drop_table('device_component_instances')
    op.drop_index(op.f('ix_consumable_usage_logs_id'), table_name='consumable_usage_logs')
    op.drop_table('consumable_usage_logs')
    op.drop_index(op.f('ix_consumable_replacement_events_id'), table_name='consumable_replacement_events')
    op.drop_table('consumable_replacement_events')
    op.drop_index(op.f('ix_blueprint_pin_details_id'), table_name='blueprint_pin_details')
    op.drop_table('blueprint_pin_details')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_roles_tier'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_plan_applicable_blueprints_id'), table_name='plan_applicable_blueprints')
    op.drop_table('plan_applicable_blueprints')
    op.drop_index(op.f('ix_organization_subscriptions_id'), table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    op.drop_index(op.f('ix_internal_blueprint_components_id'), table_name='internal_blueprint_components')
    op.drop_table('internal_blueprint_components')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_current_uuid'), table_name='devices')
    op.drop_index(op.f('ix_devices_cpu_serial'), table_name='devices')
    op.drop_index('idx_device_org_blueprint', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_blueprint_valid_pins_id'), table_name='blueprint_valid_pins')
    op.drop_table('blueprint_valid_pins')
    op.drop_index(op.f('ix_blueprint_pin_mappings_id'), table_name='blueprint_pin_mappings')
    op.drop_table('blueprint_pin_mappings')
    op.drop_index(op.f('ix_audit_log_details_id'), table_name='audit_log_details')
    op.drop_table('audit_log_details')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_user_consumables_id'), table_name='user_consumables')
    op.drop_table('user_consumables')
    op.drop_index(op.f('ix_supported_component_metadata_id'), table_name='supported_component_metadata')
    op.drop_table('supported_component_metadata')
    op.drop_index(op.f('ix_subscription_plan_features_id'), table_name='subscription_plan_features')
    op.drop_table('subscription_plan_features')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_internal_asset_purchase_records_id'), table_name='internal_asset_purchase_records')
    op.drop_table('internal_asset_purchase_records')
    op.drop_index(op.f('ix_internal_asset_inventory_id'), table_name='internal_asset_inventory')
    op.drop_table('internal_asset_inventory')
    op.drop_index(op.f('ix_hardware_blueprints_id'), table_name='hardware_blueprints')
    op.drop_table('hardware_blueprints')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_supported_components_id'), table_name='supported_components')
    op.drop_index(op.f('ix_supported_components_component_type'), table_name='supported_components')
    op.drop_table('supported_components')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_product_lines_id'), table_name='product_lines')
    op.drop_table('product_lines')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organization_types_id'), table_name='organization_types')
    op.drop_table('organization_types')
    op.drop_index(op.f('ix_internal_asset_definitions_id'), table_name='internal_asset_definitions')
    op.drop_table('internal_asset_definitions')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_certificate_name'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###
