"""Rename Device.shared_secret to hmac_key_name

Revision ID: 1aa6e71244cd
Revises: d36a525c8c12
Create Date: 2025-12-02 07:05:54.662684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa6e71244cd'
down_revision: Union[str, Sequence[str], None] = 'd36a525c8c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('hmac_key_name', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_devices_shared_secret'), table_name='devices')
    op.create_index(op.f('ix_devices_hmac_key_name'), 'devices', ['hmac_key_name'], unique=False)
    op.drop_column('devices', 'shared_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('shared_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_devices_hmac_key_name'), table_name='devices')
    op.create_index(op.f('ix_devices_shared_secret'), 'devices', ['shared_secret'], unique=False)
    op.drop_column('devices', 'hmac_key_name')
    # ### end Alembic commands ###
