"""Re-add shared_secret to User model for feature parity

Revision ID: 1dd8e43a043e
Revises: 5e5d3d057cac
Create Date: 2025-11-19 10:47:58.505949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd8e43a043e'
down_revision: Union[str, Sequence[str], None] = '5e5d3d057cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shared_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'shared_secret')
    # ### end Alembic commands ###
