"""Add new event types to log_event_type enum

Revision ID: 31eae6a6573b
Revises: 3d1aafe82b82
Create Date: 2025-12-05 06:39:10.793969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31eae6a6573b'
down_revision: Union[str, Sequence[str], None] = '3d1aafe82b82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_role_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_requests_id'), 'access_requests', ['id'], unique=False)
    op.create_index(op.f('ix_access_requests_organization_id'), 'access_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_access_requests_requested_role_id'), 'access_requests', ['requested_role_id'], unique=False)
    op.create_index(op.f('ix_access_requests_status'), 'access_requests', ['status'], unique=False)
    op.create_index(op.f('ix_access_requests_user_id'), 'access_requests', ['user_id'], unique=False)
    op.create_table('organization_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('OWNER', 'OPERATOR', 'VIEWER', name='org_device_relationship_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'device_id', 'relationship_type', name='_organization_device_uc')
    )
    op.create_index(op.f('ix_organization_devices_id'), 'organization_devices', ['id'], unique=False)
    op.execute("ALTER TYPE log_event_type ADD VALUE 'SERVER_CERTIFICATE_ACQUIRED_NEW'")
    op.execute("ALTER TYPE log_event_type ADD VALUE 'SERVER_MQTT_CERTIFICATE_ISSUED'")
    op.execute("ALTER TYPE log_event_type ADD VALUE 'DEVICE_CERTIFICATE_CREATED'")
    op.execute("ALTER TYPE log_event_type ADD VALUE 'CERTIFICATE_REVOKED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_devices_id'), table_name='organization_devices')
    op.drop_table('organization_devices')
    op.drop_index(op.f('ix_access_requests_user_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_status'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_requested_role_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_organization_id'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_id'), table_name='access_requests')
    op.drop_table('access_requests')
    # ### end Alembic commands ###
