"""Remove certificates table and related columns

Revision ID: 3d1aafe82b82
Revises: 693b26f5852a
Create Date: 2025-12-03 09:09:53.824191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d1aafe82b82'
down_revision: Union[str, Sequence[str], None] = '693b26f5852a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 'devices' 테이블의 제약조건과 컬럼을 먼저 삭제합니다.
    op.drop_constraint(op.f('devices_device_certificate_id_key'), 'devices', type_='unique')
    op.drop_constraint(op.f('devices_ca_certificate_id_fkey'), 'devices', type_='foreignkey')
    op.drop_constraint(op.f('devices_device_certificate_id_fkey'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'ca_certificate_id')
    op.drop_column('devices', 'device_certificate_id')
    
    # 2. 마지막으로 'certificates' 테이블을 삭제합니다.
    op.drop_index(op.f('ix_certificates_certificate_name'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_certificate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('ca_certificate_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('devices_device_certificate_id_fkey'), 'devices', 'certificates', ['device_certificate_id'], ['id'])
    op.create_foreign_key(op.f('devices_ca_certificate_id_fkey'), 'devices', 'certificates', ['ca_certificate_id'], ['id'])
    op.create_unique_constraint(op.f('devices_device_certificate_id_key'), 'devices', ['device_certificate_id'], postgresql_nulls_not_distinct=False)
    op.create_table('certificates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('certificate_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('certificate_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('certificates_pkey'))
    )
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_certificate_name'), 'certificates', ['certificate_name'], unique=True)
    # ### end Alembic commands ###
