"""Add is_system_locked to permission

Revision ID: 3e91f41e2be2
Revises: 83c50643cb9c
Create Date: 2026-01-16 00:11:51.950320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e91f41e2be2'
down_revision: Union[str, Sequence[str], None] = '83c50643cb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('is_system_locked', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'is_system_locked')
    # ### end Alembic commands ###
