"""refactor_system_unit_assignments2

Revision ID: 40f2540298c7
Revises: 191b9e3a7263
Create Date: 2026-02-13 04:18:54.093118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40f2540298c7'
down_revision: Union[str, Sequence[str], None] = '191b9e3a7263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. device_component_instances 인덱스 재구성 (JSONB 경로 표현식 최적화)
    # Alembic이 자동 생성 시 표현식을 약간 다르게 해석하여 재생성하려는 것이므로 안전하게 유지합니다.
    op.drop_index(op.f('ix_unique_spatial_slot'), table_name='device_component_instances')
    op.create_index('ix_unique_spatial_slot', 'device_component_instances', [sa.literal_column("((spatial_context->'grid'->>'row')), ((spatial_context->'grid'->>'col')), ((spatial_context->'grid'->>'layer'))")], unique=True)
    
    # 2. organizations.currency 타입 변경 제거
    # 에러 원인인 'currencytype' 변경 시도를 삭제합니다. 
    # 이미 이전 마이그레이션에서 'currency_type'으로 정상 반영되어 있습니다.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # currency 관련 변경 사항 삭제
    
    op.drop_index('ix_unique_spatial_slot', table_name='device_component_instances')
    op.create_index(op.f('ix_unique_spatial_slot'), 'device_component_instances', [sa.literal_column("((spatial_context -> 'grid'::text) ->> 'row'::text)"), sa.literal_column("((spatial_context -> 'grid'::text) ->> 'col'::text)"), sa.literal_column("((spatial_context -> 'grid'::text) ->> 'layer'::text)")], unique=True)
    
    # ### end Alembic commands ###