"""Remove is_editable from role_permission

Revision ID: 58e90c6f63dc
Revises: 3e91f41e2be2
Create Date: 2026-01-16 00:51:44.299212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e90c6f63dc'
down_revision: Union[str, Sequence[str], None] = '3e91f41e2be2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_permissions', 'is_editable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('is_editable', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
