"""Remove shared_secret from User model

Revision ID: 5e5d3d057cac
Revises: 9991eae0bc1b
Create Date: 2025-11-19 10:29:08.461672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e5d3d057cac'
down_revision: Union[str, Sequence[str], None] = '9991eae0bc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('UNKNOWN', 'ONLINE', 'OFFLINE', 'TIMEOUT', name='device_status').create(op.get_bind())
    op.add_column('devices', sa.Column('status', postgresql.ENUM('UNKNOWN', 'ONLINE', 'OFFLINE', 'TIMEOUT', name='device_status', create_type=False), nullable=False))
    op.drop_column('users', 'shared_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shared_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('devices', 'status')
    sa.Enum('UNKNOWN', 'ONLINE', 'OFFLINE', 'TIMEOUT', name='device_status').drop(op.get_bind())
    # ### end Alembic commands ###
