"""Update component and device models with control types and spatial context

Revision ID: 64a10a488334
Revises: e9fd63c8fd64
Create Date: 2026-01-26 08:20:48.395441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64a10a488334'
down_revision: Union[str, Sequence[str], None] = 'e9fd63c8fd64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the new ENUM type
control_type_enum = postgresql.ENUM('RANGE', 'BINARY', 'STEP', 'NONE', name='controltype')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the ENUM type in the database
    control_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('device_component_instances', sa.Column('spatial_context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False, comment='grid: {row, col, layer}, physical: {x, y, z}, operating_limits: {SLA} 등을 포함'))
    op.create_index(op.f('ix_device_component_instances_instance_name'), 'device_component_instances', ['instance_name'], unique=False)
    op.create_index('ix_unique_spatial_slot', 'device_component_instances', [sa.literal_column("(spatial_context->'grid'->>'row'), (spatial_context->'grid'->>'col'), (spatial_context->'grid'->>'layer')")], unique=True)
    op.add_column('supported_components', sa.Column('model_name', sa.String(length=100), nullable=False))
    op.add_column('supported_components', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('supported_components', sa.Column('control_type', control_type_enum, nullable=False))
    op.add_column('supported_components', sa.Column('min_value', sa.Float(), nullable=False))
    op.add_column('supported_components', sa.Column('max_value', sa.Float(), nullable=False))
    op.add_column('supported_components', sa.Column('unit', sa.String(length=20), nullable=True))
    op.alter_column('supported_components', 'display_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_index(op.f('ix_supported_components_component_type'), table_name='supported_components')
    op.create_unique_constraint('_model_manufacturer_uc', 'supported_components', ['model_name', 'manufacturer'])
    op.create_index(op.f('ix_supported_components_category'), 'supported_components', ['category'], unique=False)
    op.create_index(op.f('ix_supported_components_manufacturer'), 'supported_components', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_supported_components_model_name'), 'supported_components', ['model_name'], unique=False)
    op.create_index(op.f('ix_supported_components_telemetry_category'), 'supported_components', ['telemetry_category'], unique=False)
    op.drop_column('supported_components', 'component_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supported_components', sa.Column('component_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_supported_components_telemetry_category'), table_name='supported_components')
    op.drop_index(op.f('ix_supported_components_model_name'), table_name='supported_components')
    op.drop_index(op.f('ix_supported_components_manufacturer'), table_name='supported_components')
    op.drop_index(op.f('ix_supported_components_category'), table_name='supported_components')
    op.drop_constraint('_model_manufacturer_uc', 'supported_components', type_='unique')
    op.create_index(op.f('ix_supported_components_component_type'), 'supported_components', ['component_type'], unique=True)
    op.alter_column('supported_components', 'display_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('supported_components', 'unit')
    op.drop_column('supported_components', 'max_value')
    op.drop_column('supported_components', 'min_value')
    op.drop_column('supported_components', 'control_type')
    op.drop_column('supported_components', 'manufacturer')
    op.drop_column('supported_components', 'model_name')
    op.drop_index('ix_unique_spatial_slot', table_name='device_component_instances')
    op.drop_index(op.f('ix_device_component_instances_instance_name'), table_name='device_component_instances')
    op.drop_column('device_component_instances', 'spatial_context')
    
    # Drop the ENUM type
    control_type_enum.drop(op.get_bind(), checkfirst=True)
    
    # ### end Alembic commands ###
