"""rename_uuid_to_current_uuid

Revision ID: 667ad21b6152
Revises: 015d33df0869
Create Date: 2026-02-12 00:56:18.230300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667ad21b6152'
down_revision: Union[str, Sequence[str], None] = '015d33df0869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unique_spatial_slot'), table_name='device_component_instances')
    op.create_index('ix_unique_spatial_slot', 'device_component_instances', [sa.literal_column("((spatial_context->'grid'->>'row')), ((spatial_context->'grid'->>'col')), ((spatial_context->'grid'->>'layer'))")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_spatial_slot', table_name='device_component_instances')
    op.create_index(op.f('ix_unique_spatial_slot'), 'device_component_instances', [sa.literal_column("((spatial_context -> 'grid'::text) ->> 'row'::text)"), sa.literal_column("((spatial_context -> 'grid'::text) ->> 'col'::text)"), sa.literal_column("((spatial_context -> 'grid'::text) ->> 'layer'::text)")], unique=True)
    # ### end Alembic commands ###
