"""Add recovery token and status to device model

Revision ID: 693b26f5852a
Revises: 1aa6e71244cd
Create Date: 2025-12-03 07:34:05.453736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693b26f5852a'
down_revision: Union[str, Sequence[str], None] = '1aa6e71244cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('recovery_token', sa.String(length=255), nullable=True))
    op.add_column('devices', sa.Column('recovery_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_devices_recovery_token'), 'devices', ['recovery_token'], unique=True)
    # ENUM 타입에 'RECOVERY_NEEDED' 값 추가 (타입 이름 수정)
    op.execute("ALTER TYPE device_status ADD VALUE 'RECOVERY_NEEDED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    참고: ENUM 값 삭제는 복잡하고 위험할 수 있어 일반적으로 downgrade에서는 생략하거나
    데이터 마이그레이션 등 안전한 방법을 사용합니다. 여기서는 간단히 생략합니다.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_recovery_token'), table_name='devices')
    op.drop_column('devices', 'recovery_token_expires_at')
    op.drop_column('devices', 'recovery_token')
    # ### end Alembic commands ###
