"""Add is_editable to role_permission

Revision ID: 83c50643cb9c
Revises: 07999c706224
Create Date: 2026-01-15 23:27:00.664853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c50643cb9c'
down_revision: Union[str, Sequence[str], None] = '07999c706224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('is_editable', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_permissions', 'is_editable')
    # ### end Alembic commands ###
