"""Add ui_group to permission

Revision ID: 8c13b540a9a4
Revises: 58e90c6f63dc
Create Date: 2026-01-18 23:25:04.164325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c13b540a9a4'
down_revision: Union[str, Sequence[str], None] = '58e90c6f63dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('ui_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'ui_group')
    # ### end Alembic commands ###
