"""Add 2FA enabled flag to user

Revision ID: 9991eae0bc1b
Revises: 047a4435bd80
Create Date: 2025-11-13 23:56:03.750655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9991eae0bc1b'
down_revision: Union[str, Sequence[str], None] = '047a4435bd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_two_factor_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_two_factor_enabled')
    # ### end Alembic commands ###
