"""Introduce ObservationSnapshot and link models

Revision ID: ac9de54ed9d0
Revises: 64a10a488334
Create Date: 2026-01-26 09:27:19.508951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac9de54ed9d0'
down_revision: Union[str, Sequence[str], None] = '64a10a488334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observation_snapshots',
    sa.Column('id', sa.String(length=255), nullable=False, comment='고유 스냅샷 ID (예: 20260126T120000Z_unit123)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('system_unit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['system_unit_id'], ['system_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_snapshots_id'), 'observation_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_observation_snapshots_system_unit_id'), 'observation_snapshots', ['system_unit_id'], unique=False)
    op.drop_index(op.f('ix_action_logs_snapshot_id'), table_name='action_logs')
    op.create_foreign_key(None, 'action_logs', 'observation_snapshots', ['snapshot_id'], ['id'])
    op.drop_index(op.f('ix_unique_spatial_slot'), table_name='device_component_instances')
    op.create_index('ix_unique_spatial_slot', 'device_component_instances', [sa.literal_column("(spatial_context->'grid'->>'row'), (spatial_context->'grid'->>'col'), (spatial_context->'grid'->>'layer')")], unique=True)
    op.drop_index(op.f('ix_image_registries_snapshot_id'), table_name='image_registries')
    op.create_foreign_key(None, 'image_registries', 'observation_snapshots', ['snapshot_id'], ['id'])
    op.drop_index(op.f('ix_telemetry_data_snapshot_id'), table_name='telemetry_data')
    op.create_foreign_key(None, 'telemetry_data', 'observation_snapshots', ['snapshot_id'], ['id'])
    op.add_column('vision_features', sa.Column('snapshot_id', sa.String(length=255), nullable=False, comment='RL State 구성을 위한 스냅샷 외래키'))
    op.alter_column('vision_features', 'vector_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='추출된 고차원 벡터 데이터',
               existing_nullable=False)
    op.alter_column('vision_features', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               comment='사용된 모델 버전',
               existing_nullable=False)
    op.create_index('idx_vision_snapshot_id', 'vision_features', ['snapshot_id'], unique=False)
    op.create_foreign_key(None, 'vision_features', 'observation_snapshots', ['snapshot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vision_features', type_='foreignkey')
    op.drop_index('idx_vision_snapshot_id', table_name='vision_features')
    op.alter_column('vision_features', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='사용된 모델 버전',
               existing_nullable=False)
    op.alter_column('vision_features', 'vector_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='추출된 고차원 벡터 데이터',
               existing_nullable=False)
    op.drop_column('vision_features', 'snapshot_id')
    op.drop_constraint(None, 'telemetry_data', type_='foreignkey')
    op.create_index(op.f('ix_telemetry_data_snapshot_id'), 'telemetry_data', ['snapshot_id'], unique=False)
    op.drop_constraint(None, 'image_registries', type_='foreignkey')
    op.create_index(op.f('ix_image_registries_snapshot_id'), 'image_registries', ['snapshot_id'], unique=False)
    op.drop_index('ix_unique_spatial_slot', table_name='device_component_instances')
    op.create_index(op.f('ix_unique_spatial_slot'), 'device_component_instances', [sa.literal_column("((spatial_context -> 'grid'::text) ->> 'row'::text)"), sa.literal_column("((spatial_context -> 'grid'::text) ->> 'col'::text)"), sa.literal_column("((spatial_context -> 'grid'::text) ->> 'layer'::text)")], unique=True)
    op.drop_constraint(None, 'action_logs', type_='foreignkey')
    op.create_index(op.f('ix_action_logs_snapshot_id'), 'action_logs', ['snapshot_id'], unique=False)
    op.drop_index(op.f('ix_observation_snapshots_system_unit_id'), table_name='observation_snapshots')
    op.drop_index(op.f('ix_observation_snapshots_id'), table_name='observation_snapshots')
    op.drop_table('observation_snapshots')
    # ### end Alembic commands ###
