"""Add role CRUD event types to log enum

Revision ID: b57010048893
Revises: 1337bad63175
Create Date: 2025-12-23 01:13:52.602510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57010048893'
down_revision: Union[str, Sequence[str], None] = '1337bad63175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE log_event_type ADD VALUE IF NOT EXISTS 'ROLE_CREATED'")
    op.execute("ALTER TYPE log_event_type ADD VALUE IF NOT EXISTS 'ROLE_UPDATED'")
    op.execute("ALTER TYPE log_event_type ADD VALUE IF NOT EXISTS 'ROLE_DELETED'")
    op.execute("ALTER TYPE log_event_type ADD VALUE IF NOT EXISTS 'ROLE_PERMISSIONS_UPDATED'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
