"""Update AccessRequest model with Mapped hints

Revision ID: b7484d83c8e5
Revises: b57010048893
Create Date: 2025-12-30 04:03:51.201007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7484d83c8e5'
down_revision: Union[str, Sequence[str], None] = 'b57010048893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_requests', sa.Column('type', sa.String(length=20), nullable=False))
    op.add_column('access_requests', sa.Column('initiated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('access_requests', sa.Column('verification_code', sa.String(), nullable=True))
    op.add_column('access_requests', sa.Column('verification_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_access_requests_initiated_by_user_id'), 'access_requests', ['initiated_by_user_id'], unique=False)
    op.create_index(op.f('ix_access_requests_type'), 'access_requests', ['type'], unique=False)
    op.create_foreign_key(None, 'access_requests', 'users', ['initiated_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_requests', type_='foreignkey')
    op.drop_index(op.f('ix_access_requests_type'), table_name='access_requests')
    op.drop_index(op.f('ix_access_requests_initiated_by_user_id'), table_name='access_requests')
    op.drop_column('access_requests', 'verification_code_expires_at')
    op.drop_column('access_requests', 'verification_code')
    op.drop_column('access_requests', 'initiated_by_user_id')
    op.drop_column('access_requests', 'type')
    # ### end Alembic commands ###
