"""Add is_active column to devices for soft delete

Revision ID: c5e8f442e768
Revises: 1dd8e43a043e
Create Date: 2025-11-20 01:27:41.646160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5e8f442e768'
down_revision: Union[str, Sequence[str], None] = '1dd8e43a043e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_active')
    # ### end Alembic commands ###
