"""Add shared_secret to device and remove from user

Revision ID: d36a525c8c12
Revises: c5e8f442e768
Create Date: 2025-12-02 03:59:26.817041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd36a525c8c12'
down_revision: Union[str, Sequence[str], None] = 'c5e8f442e768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_requests_id'), table_name='registration_requests')
    op.drop_table('registration_requests')
    op.drop_index(op.f('ix_upgrade_requests_id'), table_name='upgrade_requests')
    op.drop_table('upgrade_requests')
    op.add_column('devices', sa.Column('shared_secret', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_device_org_blueprint'), table_name='devices')
    op.create_index(op.f('ix_devices_shared_secret'), 'devices', ['shared_secret'], unique=False)
    op.drop_constraint(op.f('devices_organization_id_fkey'), 'devices', type_='foreignkey')
    op.drop_column('devices', 'organization_id')
    op.add_column('roles', sa.Column('max_headcount', sa.Integer(), nullable=True))
    op.drop_column('users', 'shared_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shared_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('roles', 'max_headcount')
    op.add_column('devices', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('devices_organization_id_fkey'), 'devices', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_devices_shared_secret'), table_name='devices')
    op.create_index(op.f('idx_device_org_blueprint'), 'devices', ['organization_id', 'hardware_blueprint_id'], unique=False)
    op.drop_column('devices', 'shared_secret')
    op.create_table('upgrade_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('reviewed_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requested_role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['requested_role_id'], ['roles.id'], name=op.f('upgrade_requests_requested_role_id_fkey')),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], name=op.f('upgrade_requests_reviewed_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('upgrade_requests_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('upgrade_requests_pkey'))
    )
    op.create_index(op.f('ix_upgrade_requests_id'), 'upgrade_requests', ['id'], unique=False)
    op.create_table('registration_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('approved_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requested_role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('registration_requests_approved_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['requested_role_id'], ['roles.id'], name=op.f('registration_requests_requested_role_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('registration_requests_pkey')),
    sa.UniqueConstraint('email', name=op.f('registration_requests_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('registration_requests_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_registration_requests_id'), 'registration_requests', ['id'], unique=False)
    # ### end Alembic commands ###
