"""Rename type_name to name in organization_type

Revision ID: d81488a4be1a
Revises: 31eae6a6573b
Create Date: 2025-12-19 03:50:56.161399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd81488a4be1a'
down_revision: Union[str, Sequence[str], None] = '31eae6a6573b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_types', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint(op.f('organization_types_type_name_key'), 'organization_types', type_='unique')
    op.create_unique_constraint(None, 'organization_types', ['name'])
    op.drop_column('organization_types', 'type_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_types', sa.Column('type_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_types', type_='unique')
    op.create_unique_constraint(op.f('organization_types_type_name_key'), 'organization_types', ['type_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('organization_types', 'name')
    # ### end Alembic commands ###
