"""Refactor telemetry, image, and action models for snapshotsync

Revision ID: e9fd63c8fd64
Revises: ed1ce76fd327
Create Date: 2026-01-26 02:29:35.610659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9fd63c8fd64'
down_revision: Union[str, Sequence[str], None] = 'ed1ce76fd327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action_logs', sa.Column('snapshot_id', sa.String(), nullable=True, comment='명령 시점의 상태(이미지+센서) 동기화 키'))
    op.alter_column('action_logs', 'parameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('action_logs', 'execution_result',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='장치 피드백, 에러 메시지 등',
               existing_nullable=True)
    op.create_index('idx_action_snapshot_id', 'action_logs', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_action_logs_snapshot_id'), 'action_logs', ['snapshot_id'], unique=False)
    
    op.add_column('image_registries', sa.Column('snapshot_id', sa.String(), nullable=False, comment='센서 및 Action 데이터와 동기화를 위한 고유 키'))
    op.alter_column('image_registries', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               comment='S3/MinIO 저장 경로',
               existing_nullable=False)
    op.alter_column('image_registries', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               comment='이미지 무결성 체크용 해시',
               existing_nullable=True)
    op.alter_column('image_registries', 'image_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment='카메라 설정 등 가변 메타데이터',
               existing_nullable=True)
    op.create_index('idx_image_snapshot_id', 'image_registries', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_image_registries_snapshot_id'), 'image_registries', ['snapshot_id'], unique=False)
    op.add_column('telemetry_data', sa.Column('snapshot_id', sa.String(), nullable=False, comment='이미지 및 Action 데이터와 동기화를 위한 고유 키'))
    op.add_column('telemetry_data', sa.Column('avg_value', sa.Float(), nullable=False, comment='평균'))
    op.add_column('telemetry_data', sa.Column('min_value', sa.Float(), nullable=False, comment='최소값'))
    op.add_column('telemetry_data', sa.Column('max_value', sa.Float(), nullable=False, comment='최대값'))
    op.add_column('telemetry_data', sa.Column('std_dev', sa.Float(), nullable=False, comment='표준편차 (안정성 지표)'))
    op.add_column('telemetry_data', sa.Column('slope', sa.Float(), nullable=False, comment='기울기 (추세 지표)'))
    op.add_column('telemetry_data', sa.Column('sample_count', sa.Integer(), nullable=False, comment='통계에 사용된 샘플 수'))
    op.add_column('telemetry_data', sa.Column('extra_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='특화 데이터 (예: 적산 온도, 사분위수 등)'))
    op.alter_column('telemetry_data', 'metric_name',
               existing_type=sa.VARCHAR(length=100),
               comment='측정 항목명 (예: temp, vibration, co2)',
               existing_nullable=False)
    op.alter_column('telemetry_data', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment='측정 단위 (예: °C, %)',
               existing_nullable=True)
    op.create_index('idx_telemetry_snapshot_id', 'telemetry_data', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_telemetry_data_metric_name'), 'telemetry_data', ['metric_name'], unique=False)
    op.create_index(op.f('ix_telemetry_data_snapshot_id'), 'telemetry_data', ['snapshot_id'], unique=False)
    op.drop_column('telemetry_data', 'timestamp')
    op.drop_column('telemetry_data', 'metric_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_data', sa.Column('metric_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('telemetry_data', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_telemetry_data_snapshot_id'), table_name='telemetry_data')
    op.drop_index(op.f('ix_telemetry_data_metric_name'), table_name='telemetry_data')
    op.drop_index('idx_telemetry_snapshot_id', table_name='telemetry_data')
    op.alter_column('telemetry_data', 'unit',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='측정 단위 (예: °C, %)',
               existing_nullable=True)
    op.alter_column('telemetry_data', 'metric_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='측정 항목명 (예: temp, vibration, co2)',
               existing_nullable=False)
    op.drop_column('telemetry_data', 'extra_stats')
    op.drop_column('telemetry_data', 'sample_count')
    op.drop_column('telemetry_data', 'slope')
    op.drop_column('telemetry_data', 'std_dev')
    op.drop_column('telemetry_data', 'max_value')
    op.drop_column('telemetry_data', 'min_value')
    op.drop_column('telemetry_data', 'avg_value')
    op.drop_column('telemetry_data', 'snapshot_id')
    op.drop_index(op.f('ix_image_registries_snapshot_id'), table_name='image_registries')
    op.drop_index('idx_image_snapshot_id', table_name='image_registries')
    op.alter_column('image_registries', 'image_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='카메라 설정 등 가변 메타데이터',
               existing_nullable=True)
    op.alter_column('image_registries', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='이미지 무결성 체크용 해시',
               existing_nullable=True)
    op.alter_column('image_registries', 'storage_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='S3/MinIO 저장 경로',
               existing_nullable=False)
    op.drop_column('image_registries', 'snapshot_id')
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.Enum('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', 'SERVER_MQTT_CERTIFICATE_ISSUED', 'DEVICE_CERTIFICATE_CREATED', 'CERTIFICATE_REVOKED', 'SERVER_CERTIFICATE_ACQUIRED_NEW', 'SERVER_CERTIFICATE_REUSED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'ACCESS_REQUEST_CREATED', 'ACCESS_REQUEST_UPDATED', 'ACCESS_REQUEST_DELETED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REVOKED', 'USER_LOGIN_FAILED', name='audit_log_event_type'),
               type_=postgresql.ENUM('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', 'SERVER_CERTIFICATE_ACQUIRED_NEW', 'SERVER_MQTT_CERTIFICATE_ISSUED', 'DEVICE_CERTIFICATE_CREATED', 'CERTIFICATE_REVOKED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED', 'ROLE_PERMISSIONS_UPDATED', 'ACCESS_REQUEST_CREATED', 'ACCESS_REQUEST_UPDATED', 'ACCESS_REQUEST_DELETED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REVOKED', 'USER_LOGIN_FAILED', 'SERVER_CERTIFICATE_REUSED', name='log_event_type'),
               existing_nullable=False)
    op.drop_index(op.f('ix_action_logs_snapshot_id'), table_name='action_logs')
    op.drop_index('idx_action_snapshot_id', table_name='action_logs')
    op.alter_column('action_logs', 'execution_result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='장치 피드백, 에러 메시지 등',
               existing_nullable=True)
    op.alter_column('action_logs', 'parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('action_logs', 'snapshot_id')
    # ### end Alembic commands ###
