"""Add SERVER_CERTIFICATE_REUSED to log_event_type enum

Revision ID: ed1ce76fd327
Revises: 5c245488e302
Create Date: 2026-01-26 00:43:21.674640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed1ce76fd327'
down_revision: Union[str, Sequence[str], None] = '5c245488e302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE log_event_type ADD VALUE IF NOT EXISTS 'SERVER_CERTIFICATE_REUSED'")
    
    # The autogenerated code for altering enums is complex and can fail.
    # The simple ADD VALUE is sufficient and safer.
    # op.alter_column('audit_logs', 'event_type',
    #            existing_type=postgresql.ENUM('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', 'SERVER_CERTIFICATE_ACQUIRED_NEW', 'SERVER_MQTT_CERTIFICATE_ISSUED', 'DEVICE_CERTIFICATE_CREATED', 'CERTIFICATE_REVOKED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED', 'ROLE_PERMISSIONS_UPDATED', 'ACCESS_REQUEST_CREATED', 'ACCESS_REQUEST_UPDATED', 'ACCESS_REQUEST_DELETED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REVOKED', 'USER_LOGIN_FAILED', name='log_event_type'),
    #            type_=sa.Enum('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', 'SERVER_MQTT_CERTIFICATE_ISSUED', 'DEVICE_CERTIFICATE_CREATED', 'CERTIFICATE_REVOKED', 'SERVER_CERTIFICATE_ACQUIRED_NEW', 'SERVER_CERTIFICATE_REUSED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'ACCESS_REQUEST_CREATED', 'ACCESS_REQUEST_UPDATED', 'ACCESS_REQUEST_DELETED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REVOKED', 'USER_LOGIN_FAILED', name='audit_log_event_type'),
    #            existing_nullable=False)
    
    op.create_table('plan_applicable_product_lines',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subscription_plan_id', sa.BigInteger(), nullable=False),
    sa.Column('product_line_id', sa.BigInteger(), nullable=False),
    sa.Column('max_unit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_line_id'], ['product_lines.id'], ),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_plan_id', 'product_line_id', name='_plan_product_line_uc')
    )
    op.create_index(op.f('ix_plan_applicable_product_lines_id'), 'plan_applicable_product_lines', ['id'], unique=False)
    op.create_table('device_role_assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.BigInteger(), nullable=False),
    sa.Column('system_unit_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['device_roles.id'], ),
    sa.ForeignKeyConstraint(['system_unit_id'], ['system_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'role_id', 'system_unit_id', name='_device_role_unit_uc')
    )
    op.create_index(op.f('ix_device_role_assignments_id'), 'device_role_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_device_role_assignments_system_unit_id'), 'device_role_assignments', ['system_unit_id'], unique=False)
    
    # Corrected order: Drop dependent table 'image_analyses' first.
    op.drop_index(op.f('ix_image_analyses_id'), table_name='image_analyses')
    op.drop_table('image_analyses')

    op.drop_index(op.f('ix_consumable_replacement_events_id'), table_name='consumable_replacement_events')
    op.drop_table('consumable_replacement_events')
    op.drop_index(op.f('ix_production_events_id'), table_name='production_events')
    op.drop_table('production_events')
    op.drop_index(op.f('ix_internal_component_replacement_events_id'), table_name='internal_component_replacement_events')
    op.drop_table('internal_component_replacement_events')
    op.drop_index(op.f('ix_plan_applicable_blueprints_id'), table_name='plan_applicable_blueprints')
    op.drop_table('plan_applicable_blueprints')
    op.alter_column('access_requests', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('access_requests', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('access_requests', 'requested_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('access_requests', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('access_requests', 'initiated_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('access_requests', 'reviewed_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.add_column('action_logs', sa.Column('model_id', sa.BigInteger(), nullable=True))
    op.add_column('action_logs', sa.Column('parameters', sa.JSON(), nullable=True))
    op.add_column('action_logs', sa.Column('execution_result', sa.JSON(), nullable=True))
    op.add_column('action_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('action_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('action_logs', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_action_logs_actor_type'), 'action_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_action_logs_id'), 'action_logs', ['id'], unique=False)
    op.create_index(op.f('ix_action_logs_system_unit_id'), 'action_logs', ['system_unit_id'], unique=False)
    op.create_index(op.f('ix_action_logs_user_id'), 'action_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'action_logs', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'action_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'action_logs', 'system_units', ['system_unit_id'], ['id'])
    op.alter_column('alert_events', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('alert_events', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('alert_events', 'acknowledged_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('alert_events', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('alert_events', 'alert_rule_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('alert_rules', sa.Column('system_unit_id', sa.BigInteger(), nullable=False))
    op.alter_column('alert_rules', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('alert_rules', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True)
    op.alter_column('alert_rules', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index(op.f('ix_alert_rules_device_id'), 'alert_rules', ['device_id'], unique=False)
    op.create_index(op.f('ix_alert_rules_system_unit_id'), 'alert_rules', ['system_unit_id'], unique=False)
    op.create_foreign_key(None, 'alert_rules', 'system_units', ['system_unit_id'], ['id'])
    op.alter_column('audit_log_details', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_log_details', 'audit_log_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_logs', 'event_type',
               existing_type=postgresql.ENUM('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', 'SERVER_CERTIFICATE_ACQUIRED_NEW', 'SERVER_MQTT_CERTIFICATE_ISSUED', 'DEVICE_CERTIFICATE_CREATED', 'CERTIFICATE_REVOKED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED', 'ROLE_PERMISSIONS_UPDATED', 'ACCESS_REQUEST_CREATED', 'ACCESS_REQUEST_UPDATED', 'ACCESS_REQUEST_DELETED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REVOKED', 'USER_LOGIN_FAILED', name='log_event_type'),
               type_=sa.Enum('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', 'SERVER_MQTT_CERTIFICATE_ISSUED', 'DEVICE_CERTIFICATE_CREATED', 'CERTIFICATE_REVOKED', 'SERVER_CERTIFICATE_ACQUIRED_NEW', 'SERVER_CERTIFICATE_REUSED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'ACCESS_REQUEST_CREATED', 'ACCESS_REQUEST_UPDATED', 'ACCESS_REQUEST_DELETED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REVOKED', 'USER_LOGIN_FAILED', name='log_event_type'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'log_level',
               existing_type=postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'),
               comment=None,
               existing_comment='로그 심각도 (선택적)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='로그 설명/메시지',
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.alter_column('blueprint_pin_details', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('blueprint_pin_details', 'blueprint_pin_mapping_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('blueprint_pin_mappings', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('blueprint_pin_mappings', 'hardware_blueprint_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('blueprint_pin_mappings', 'supported_component_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('blueprint_valid_pins', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('blueprint_valid_pins', 'hardware_blueprint_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('consumable_usage_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('consumable_usage_logs', 'log_level',
               existing_type=postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'),
               comment=None,
               existing_comment='로그 심각도 (선택적)',
               existing_nullable=True)
    op.alter_column('consumable_usage_logs', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='로그 설명/메시지',
               existing_nullable=True)
    op.alter_column('consumable_usage_logs', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('consumable_usage_logs', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('consumable_usage_logs', 'user_consumable_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('device_component_instances', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('device_component_instances', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('device_component_instances', 'supported_component_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('device_component_pin_mappings', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('device_component_pin_mappings', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('device_component_pin_mappings', 'device_component_instance_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('device_logs', sa.Column('log_metadata', sa.JSON(), nullable=True))
    op.alter_column('device_logs', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('device_logs', 'log_level',
               existing_type=postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'),
               comment=None,
               existing_comment='로그 심각도 (선택적)',
               existing_nullable=True)
    op.alter_column('device_logs', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='로그 설명/메시지',
               existing_nullable=True)
    op.alter_column('device_logs', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_column('device_logs', 'metadata_json')
    op.add_column('device_roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('device_roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('device_roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('device_roles_role_key_key'), 'device_roles', type_='unique')
    op.create_index(op.f('ix_device_roles_id'), 'device_roles', ['id'], unique=False)
    op.create_index(op.f('ix_device_roles_role_key'), 'device_roles', ['role_key'], unique=True)
    op.alter_column('devices', 'hardware_blueprint_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('devices', 'system_unit_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_devices_system_unit_id'), 'devices', ['system_unit_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'system_units', ['system_unit_id'], ['id'])
    op.alter_column('firmware_updates', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('firmware_updates', 'initiated_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('firmware_updates', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('firmware_updates', 'hardware_blueprint_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('governance_rules', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('governance_rules', 'actor_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('governance_rules', 'target_role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('hardware_blueprints', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('hardware_blueprints', 'product_line_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('image_registries', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('image_registries', sa.Column('image_metadata', sa.JSON(), nullable=True))
    op.add_column('image_registries', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('image_registries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_image_registries_file_hash'), 'image_registries', ['file_hash'], unique=False)
    op.create_index(op.f('ix_image_registries_id'), 'image_registries', ['id'], unique=False)
    op.create_index(op.f('ix_image_registries_system_unit_id'), 'image_registries', ['system_unit_id'], unique=False)
    op.create_foreign_key(None, 'image_registries', 'system_units', ['system_unit_id'], ['id'])
    op.create_foreign_key(None, 'image_registries', 'devices', ['device_id'], ['id'])
    op.alter_column('internal_asset_definitions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('internal_asset_inventory', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('internal_asset_inventory', 'last_updated_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('internal_asset_inventory', 'asset_definition_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('internal_asset_purchase_records', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('internal_asset_purchase_records', 'recorded_by_user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('internal_asset_purchase_records', 'asset_definition_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('internal_blueprint_components', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('internal_blueprint_components', 'hardware_blueprint_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('internal_blueprint_components', 'asset_definition_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('organization_devices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_devices', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('organization_devices', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('organization_subscriptions', sa.Column('system_unit_id', sa.BigInteger(), nullable=True))
    op.add_column('organization_subscriptions', sa.Column('subscription_plan_id', sa.BigInteger(), nullable=False))
    op.alter_column('organization_subscriptions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organization_subscriptions', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.drop_constraint(op.f('_org_plan_uc'), 'organization_subscriptions', type_='unique')
    op.create_unique_constraint('_org_plan_unit_uc', 'organization_subscriptions', ['organization_id', 'subscription_plan_id', 'system_unit_id'])
    op.create_unique_constraint(None, 'organization_subscriptions', ['system_unit_id'])
    op.drop_constraint(op.f('organization_subscriptions_plan_id_fkey'), 'organization_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'organization_subscriptions', 'subscription_plans', ['subscription_plan_id'], ['id'])
    op.create_foreign_key(None, 'organization_subscriptions', 'system_units', ['system_unit_id'], ['id'])
    op.drop_column('organization_subscriptions', 'plan_id')
    op.alter_column('organization_types', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('organizations', 'organization_type_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_column('organizations', 'website_url')
    op.drop_column('organizations', 'tax_id')
    op.drop_column('organizations', 'billing_address')
    op.drop_column('organizations', 'business_type')
    op.drop_column('organizations', 'representative_name')
    op.alter_column('product_lines', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('roles', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('schedules', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('schedules', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('schedules', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('subscription_plan_features', sa.Column('subscription_plan_id', sa.BigInteger(), nullable=False))
    op.alter_column('subscription_plan_features', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(op.f('_plan_feature_uc'), 'subscription_plan_features', type_='unique')
    op.create_unique_constraint('_plan_feature_uc', 'subscription_plan_features', ['subscription_plan_id', 'feature_key'])
    op.drop_constraint(op.f('subscription_plan_features_plan_id_fkey'), 'subscription_plan_features', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_plan_features', 'subscription_plans', ['subscription_plan_id'], ['id'])
    op.drop_column('subscription_plan_features', 'plan_id')
    op.add_column('subscription_plans', sa.Column('trial_period_days', sa.Integer(), nullable=True))
    op.alter_column('subscription_plans', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('supported_component_metadata', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('supported_component_metadata', 'supported_component_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('supported_components', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('system_units', sa.Column('unit_config', sa.JSON(), nullable=True))
    op.add_column('system_units', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('system_units', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('system_units', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('system_units', sa.Column('product_line_id', sa.BigInteger(), nullable=False))
    op.add_column('system_units', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_system_units_id'), 'system_units', ['id'], unique=False)
    op.create_index(op.f('ix_system_units_user_id'), 'system_units', ['user_id'], unique=False)
    op.create_foreign_key(None, 'system_units', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'system_units', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'system_units', 'product_lines', ['product_line_id'], ['id'])
    op.add_column('telemetry_data', sa.Column('system_unit_id', sa.BigInteger(), nullable=False))
    op.alter_column('telemetry_data', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telemetry_data', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_index('idx_telemetry_system_unit_time', 'telemetry_data', ['system_unit_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_data_system_unit_id'), 'telemetry_data', ['system_unit_id'], unique=False)
    op.create_foreign_key(None, 'telemetry_data', 'system_units', ['system_unit_id'], ['id'])
    op.alter_column('telemetry_metadata', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telemetry_metadata', 'telemetry_data_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('trigger_rules', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('trigger_rules', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('trigger_rules', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('unit_activity_logs', sa.Column('activity_payload', sa.JSON(), nullable=False))
    op.add_column('unit_activity_logs', sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('unit_activity_logs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('unit_activity_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('unit_activity_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('unit_activity_logs', sa.Column('device_id', sa.BigInteger(), nullable=False))
    op.add_column('unit_activity_logs', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_unit_activity_logs_activity_type'), 'unit_activity_logs', ['activity_type'], unique=False)
    op.create_index(op.f('ix_unit_activity_logs_id'), 'unit_activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_unit_activity_logs_system_unit_id'), 'unit_activity_logs', ['system_unit_id'], unique=False)
    op.create_foreign_key(None, 'unit_activity_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'unit_activity_logs', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'unit_activity_logs', 'system_units', ['system_unit_id'], ['id'])
    op.alter_column('user_consumables', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_consumables', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_consumables', 'asset_definition_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_devices', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_devices', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_devices', 'device_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_organization_roles', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_organization_roles', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('user_organization_roles', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.alter_column('user_organization_roles', 'role_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.add_column('user_subscriptions', sa.Column('system_unit_id', sa.BigInteger(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('max_devices', sa.Integer(), nullable=True))
    op.add_column('user_subscriptions', sa.Column('subscription_plan_id', sa.BigInteger(), nullable=False))
    op.alter_column('user_subscriptions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_subscriptions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint(op.f('_user_plan_uc'), 'user_subscriptions', type_='unique')
    op.create_unique_constraint('_user_plan_unit_uc', 'user_subscriptions', ['user_id', 'subscription_plan_id', 'system_unit_id'])
    op.create_unique_constraint(None, 'user_subscriptions', ['system_unit_id'])
    op.drop_constraint(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'user_subscriptions', 'system_units', ['system_unit_id'], ['id'])
    op.create_foreign_key(None, 'user_subscriptions', 'subscription_plans', ['subscription_plan_id'], ['id'])
    op.drop_column('user_subscriptions', 'plan_id')
    op.add_column('vision_features', sa.Column('model_version', sa.String(length=50), nullable=False))
    op.add_column('vision_features', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vision_features', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('vision_features', sa.Column('system_unit_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_vision_features_id'), 'vision_features', ['id'], unique=False)
    op.create_index(op.f('ix_vision_features_image_id'), 'vision_features', ['image_id'], unique=False)
    op.create_index(op.f('ix_vision_features_system_unit_id'), 'vision_features', ['system_unit_id'], unique=False)
    op.create_foreign_key(None, 'vision_features', 'devices', ['device_id'], ['id'])
    op.create_foreign_key(None, 'vision_features', 'image_registries', ['image_id'], ['id'])
    op.create_foreign_key(None, 'vision_features', 'system_units', ['system_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vision_features', type_='foreignkey')
    op.drop_constraint(None, 'vision_features', type_='foreignkey')
    op.drop_constraint(None, 'vision_features', type_='foreignkey')
    op.drop_index(op.f('ix_vision_features_system_unit_id'), table_name='vision_features')
    op.drop_index(op.f('ix_vision_features_image_id'), table_name='vision_features')
    op.drop_index(op.f('ix_vision_features_id'), table_name='vision_features')
    op.drop_column('vision_features', 'system_unit_id')
    op.drop_column('vision_features', 'updated_at')
    op.drop_column('vision_features', 'created_at')
    op.drop_column('vision_features', 'model_version')
    op.add_column('user_subscriptions', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'user_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('user_subscriptions_plan_id_fkey'), 'user_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_constraint(None, 'user_subscriptions', type_='unique')
    op.drop_constraint('_user_plan_unit_uc', 'user_subscriptions', type_='unique')
    op.create_unique_constraint(op.f('_user_plan_uc'), 'user_subscriptions', ['user_id', 'plan_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_subscriptions', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_subscriptions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('user_subscriptions', 'subscription_plan_id')
    op.drop_column('user_subscriptions', 'max_devices')
    op.drop_column('user_subscriptions', 'system_unit_id')
    op.alter_column('user_organization_roles', 'role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_organization_roles', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_organization_roles', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_organization_roles', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_devices', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_devices', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_devices', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user_consumables', 'asset_definition_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_consumables', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('user_consumables', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'unit_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'unit_activity_logs', type_='foreignkey')
    op.drop_constraint(None, 'unit_activity_logs', type_='foreignkey')
    op.drop_index(op.f('ix_unit_activity_logs_system_unit_id'), table_name='unit_activity_logs')
    op.drop_index(op.f('ix_unit_activity_logs_id'), table_name='unit_activity_logs')
    op.drop_index(op.f('ix_unit_activity_logs_activity_type'), table_name='unit_activity_logs')
    op.drop_column('unit_activity_logs', 'user_id')
    op.drop_column('unit_activity_logs', 'device_id')
    op.drop_column('unit_activity_logs', 'updated_at')
    op.drop_column('unit_activity_logs', 'created_at')
    op.drop_column('unit_activity_logs', 'description')
    op.drop_column('unit_activity_logs', 'occurred_at')
    op.drop_column('unit_activity_logs', 'activity_payload')
    op.alter_column('trigger_rules', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('trigger_rules', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('trigger_rules', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('telemetry_metadata', 'telemetry_data_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('telemetry_metadata', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'telemetry_data', type_='foreignkey')
    op.drop_index(op.f('ix_telemetry_data_system_unit_id'), table_name='telemetry_data')
    op.drop_index('idx_telemetry_system_unit_time', table_name='telemetry_data')
    op.alter_column('telemetry_data', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('telemetry_data', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('telemetry_data', 'system_unit_id')
    op.drop_constraint(None, 'system_units', type_='foreignkey')
    op.drop_constraint(None, 'system_units', type_='foreignkey')
    op.drop_constraint(None, 'system_units', type_='foreignkey')
    op.drop_index(op.f('ix_system_units_user_id'), table_name='system_units')
    op.drop_index(op.f('ix_system_units_id'), table_name='system_units')
    op.drop_column('system_units', 'user_id')
    op.drop_column('system_units', 'product_line_id')
    op.drop_column('system_units', 'updated_at')
    op.drop_column('system_units', 'created_at')
    op.drop_column('system_units', 'description')
    op.drop_column('system_units', 'unit_config')
    op.alter_column('supported_components', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('supported_component_metadata', 'supported_component_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('supported_component_metadata', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('subscription_plans', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('subscription_plans', 'trial_period_days')
    op.add_column('subscription_plan_features', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscription_plan_features', type_='foreignkey')
    op.create_foreign_key(op.f('subscription_plan_features_plan_id_fkey'), 'subscription_plan_features', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_constraint('_plan_feature_uc', 'subscription_plan_features', type_='unique')
    op.create_unique_constraint(op.f('_plan_feature_uc'), 'subscription_plan_features', ['plan_id', 'feature_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscription_plan_features', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('subscription_plan_features', 'subscription_plan_id')
    op.alter_column('schedules', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('schedules', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('schedules', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('roles', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('role_permissions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('product_lines', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('organizations', sa.Column('representative_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('business_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('billing_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('website_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('organizations', 'organization_type_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('organization_types', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('organization_subscriptions', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'organization_subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('organization_subscriptions_plan_id_fkey'), 'organization_subscriptions', 'subscription_plans', ['plan_id'], ['id'])
    op.drop_constraint(None, 'organization_subscriptions', type_='unique')
    op.drop_constraint('_org_plan_unit_uc', 'organization_subscriptions', type_='unique')
    op.create_unique_constraint(op.f('_org_plan_uc'), 'organization_subscriptions', ['organization_id', 'plan_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('organization_subscriptions', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('organization_subscriptions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('organization_subscriptions', 'subscription_plan_id')
    op.drop_column('organization_subscriptions', 'system_unit_id')
    op.alter_column('organization_devices', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('organization_devices', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('organization_devices', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('internal_blueprint_components', 'asset_definition_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('internal_blueprint_components', 'hardware_blueprint_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('internal_blueprint_components', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('internal_asset_purchase_records', 'asset_definition_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('internal_asset_purchase_records', 'recorded_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('internal_asset_purchase_records', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('internal_asset_inventory', 'asset_definition_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('internal_asset_inventory', 'last_updated_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('internal_asset_inventory', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('internal_asset_definitions', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'image_registries', type_='foreignkey')
    op.drop_constraint(None, 'image_registries', type_='foreignkey')
    op.drop_index(op.f('ix_image_registries_system_unit_id'), table_name='image_registries')
    op.drop_index(op.f('ix_image_registries_id'), table_name='image_registries')
    op.drop_index(op.f('ix_image_registries_file_hash'), table_name='image_registries')
    op.drop_column('image_registries', 'updated_at')
    op.drop_column('image_registries', 'created_at')
    op.drop_column('image_registries', 'image_metadata')
    op.drop_column('image_registries', 'file_hash')
    op.alter_column('hardware_blueprints', 'product_line_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('hardware_blueprints', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('governance_rules', 'target_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('governance_rules', 'actor_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('governance_rules', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('firmware_updates', 'hardware_blueprint_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('firmware_updates', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('firmware_updates', 'initiated_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('firmware_updates', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_system_unit_id'), table_name='devices')
    op.alter_column('devices', 'system_unit_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('devices', 'hardware_blueprint_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_device_roles_role_key'), table_name='device_roles')
    op.drop_index(op.f('ix_device_roles_id'), table_name='device_roles')
    op.create_unique_constraint(op.f('device_roles_role_key_key'), 'device_roles', ['role_key'], postgresql_nulls_not_distinct=False)
    op.drop_column('device_roles', 'updated_at')
    op.drop_column('device_roles', 'created_at')
    op.drop_column('device_roles', 'description')
    op.add_column('device_logs', sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('device_logs', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('device_logs', 'description',
               existing_type=sa.TEXT(),
               comment='로그 설명/메시지',
               existing_nullable=True)
    op.alter_column('device_logs', 'log_level',
               existing_type=postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'),
               comment='로그 심각도 (선택적)',
               existing_nullable=True)
    op.alter_column('device_logs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('device_logs', 'log_metadata')
    op.alter_column('device_component_pin_mappings', 'device_component_instance_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('device_component_pin_mappings', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('device_component_pin_mappings', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('device_component_instances', 'supported_component_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('device_component_instances', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('device_component_instances', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('consumable_usage_logs', 'user_consumable_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('consumable_usage_logs', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('consumable_usage_logs', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('consumable_usage_logs', 'description',
               existing_type=sa.TEXT(),
               comment='로그 설명/메시지',
               existing_nullable=True)
    op.alter_column('consumable_usage_logs', 'log_level',
               existing_type=postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'),
               comment='로그 심각도 (선택적)',
               existing_nullable=True)
    op.alter_column('consumable_usage_logs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('blueprint_valid_pins', 'hardware_blueprint_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('blueprint_valid_pins', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('blueprint_pin_mappings', 'supported_component_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('blueprint_pin_mappings', 'hardware_blueprint_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('blueprint_pin_mappings', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('blueprint_pin_details', 'blueprint_pin_mapping_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('blueprint_pin_details', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('audit_logs', 'description',
               existing_type=sa.TEXT(),
               comment='로그 설명/메시지',
               existing_nullable=True)
    op.alter_column('audit_logs', 'log_level',
               existing_type=postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='log_level'),
               comment='로그 심각도 (선택적)',
               existing_nullable=True)
    op.alter_column('audit_logs', 'event_type',
               existing_type=sa.Enum('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', 'SERVER_MQTT_CERTIFICATE_ISSUED', 'DEVICE_CERTIFICATE_CREATED', 'CERTIFICATE_REVOKED', 'SERVER_CERTIFICATE_ACQUIRED_NEW', 'SERVER_CERTIFICATE_REUSED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'ACCESS_REQUEST_CREATED', 'ACCESS_REQUEST_UPDATED', 'ACCESS_REQUEST_DELETED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REVOKED', 'USER_LOGIN_FAILED', name='audit_log_event_type'),
               type_=postgresql.ENUM('DEVICE', 'AUDIT', 'CONSUMABLE_USAGE', 'SERVER_CERTIFICATE_ACQUIRED_NEW', 'SERVER_MQTT_CERTIFICATE_ISSUED', 'DEVICE_CERTIFICATE_CREATED', 'CERTIFICATE_REVOKED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'ROLE_CREATED', 'ROLE_UPDATED', 'ROLE_DELETED', 'ROLE_PERMISSIONS_UPDATED', 'ACCESS_REQUEST_CREATED', 'ACCESS_REQUEST_UPDATED', 'ACCESS_REQUEST_DELETED', 'USER_ROLE_ASSIGNED', 'USER_ROLE_REVOKED', 'USER_LOGIN_FAILED', name='log_event_type'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_log_details', 'audit_log_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('audit_log_details', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'alert_rules', type_='foreignkey')
    op.drop_index(op.f('ix_alert_rules_system_unit_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_device_id'), table_name='alert_rules')
    op.alter_column('alert_rules', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('alert_rules', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('alert_rules', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('alert_rules', 'system_unit_id')
    op.alter_column('alert_events', 'alert_rule_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('alert_events', 'device_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('alert_events', 'acknowledged_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('alert_events', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('alert_events', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'action_logs', type_='foreignkey')
    op.drop_constraint(None, 'action_logs', type_='foreignkey')
    op.drop_constraint(None, 'action_logs', type_='foreignkey')
    op.drop_index(op.f('ix_action_logs_user_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_system_unit_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_actor_type'), table_name='action_logs')
    op.drop_column('action_logs', 'user_id')
    op.drop_column('action_logs', 'updated_at')
    op.drop_column('action_logs', 'created_at')
    op.drop_column('action_logs', 'execution_result')
    op.drop_column('action_logs', 'parameters')
    op.drop_column('action_logs', 'model_id')
    op.alter_column('access_requests', 'reviewed_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('access_requests', 'initiated_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('access_requests', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('access_requests', 'requested_role_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('access_requests', 'user_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('access_requests', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('image_analyses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analysis_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('detected_disease', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recommended_action', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('analysis_type', postgresql.ENUM('YOLO', 'CLASSIFICATION', 'OTHER', name='analysis_type'), autoincrement=False, nullable=False),
    sa.Column('analysis_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('production_event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['production_event_id'], ['production_events.id'], name=op.f('image_analyses_production_event_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('image_analyses_pkey'))
    )
    op.create_index(op.f('ix_image_analyses_id'), 'image_analyses', ['id'], unique=False)
    op.create_table('plan_applicable_blueprints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hardware_blueprint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], name=op.f('plan_applicable_blueprints_hardware_blueprint_id_fkey')),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('plan_applicable_blueprints_plan_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_applicable_blueprints_pkey')),
    sa.UniqueConstraint('plan_id', 'hardware_blueprint_id', name=op.f('_plan_blueprint_uc'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_plan_applicable_blueprints_id'), 'plan_applicable_blueprints', ['id'], unique=False)
    op.create_table('internal_component_replacement_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('replacement_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recorded_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('asset_definition_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['internal_asset_definitions.id'], name=op.f('internal_component_replacement_events_asset_definition_id_fkey')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('internal_component_replacement_events_device_id_fkey')),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], name=op.f('internal_component_replacement_events_recorded_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('internal_component_replacement_events_pkey'))
    )
    op.create_index(op.f('ix_internal_component_replacement_events_id'), 'internal_component_replacement_events', ['id'], unique=False)
    op.create_table('production_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_type', postgresql.ENUM('HARVEST', 'GROWTH_UPDATE', 'MAINTENANCE', name='production_event_type'), autoincrement=False, nullable=False),
    sa.Column('event_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('yield_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crop_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('growth_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hardware_blueprint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('production_events_device_id_fkey')),
    sa.ForeignKeyConstraint(['hardware_blueprint_id'], ['hardware_blueprints.id'], name=op.f('production_events_hardware_blueprint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('production_events_pkey'))
    )
    op.create_index(op.f('ix_production_events_id'), 'production_events', ['id'], unique=False)
    op.create_table('consumable_replacement_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='소모품 교체 이벤트의 고유 ID'),
    sa.Column('replacement_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_consumable_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('consumable_replacement_events_device_id_fkey')),
    sa.ForeignKeyConstraint(['user_consumable_id'], ['user_consumables.id'], name=op.f('consumable_replacement_events_user_consumable_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('consumable_replacement_events_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('consumable_replacement_events_pkey'))
    )
    op.create_index(op.f('ix_consumable_replacement_events_id'), 'consumable_replacement_events', ['id'], unique=False)
    op.drop_index(op.f('ix_device_role_assignments_system_unit_id'), table_name='device_role_assignments')
    op.drop_index(op.f('ix_device_role_assignments_id'), table_name='device_role_assignments')
    op.drop_table('device_role_assignments')
    op.drop_index(op.f('ix_plan_applicable_product_lines_id'), table_name='plan_applicable_product_lines')
    op.drop_table('plan_applicable_product_lines')
    # ### end Alembic commands ###
