"""Consolidate governance_rules creation

Revision ID: eebc1a6019e6
Revises: 2b96c28d6ffa
Create Date: 2026-01-05 10:30:31.865605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebc1a6019e6'
down_revision: Union[str, Sequence[str], None] = '2b96c28d6ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('actor_role_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_role_id', sa.Integer(), nullable=True),
    sa.Column('context', sa.Enum('SYSTEM', 'ORGANIZATION', name='governance_context_type'), nullable=False),
    sa.Column('allow', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index(op.f('ix_governance_rules_action'), 'governance_rules', ['action'], unique=False)
    op.create_index(op.f('ix_governance_rules_id'), 'governance_rules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_governance_rules_id'), table_name='governance_rules')
    op.drop_index(op.f('ix_governance_rules_action'), table_name='governance_rules')
    op.drop_table('governance_rules')
    # ### end Alembic commands ###
